Add Reporter Avatar
goatcorp/dalamud-bugbait pull request #8
Opened 2024-07-29 21:46 UTC by KazWolfe

Calculated by the reporter's IP address and hashed/peppered prior to being delivered to us.

This could allow us to ban certain IPs without any knowledge as to who we're actually banning.

Code is completely untested because I'm lazy.

2025-01-27 10:06 UTC, philpax commented on src/index.js
> +  } else if (reporterIp != null) {
`reporterIp` is not defined, did you mean `reporterId`?

2025-02-03 18:14 UTC, KhloeLeclair requested changes

2025-02-03 18:14 UTC, KhloeLeclair commented on src/index.js
> +    body.embeds[0].author["name"] = reporter;
This change will result in an error being thrown because `body.embeds[0].author` is undefined. Easiest fix would seem to be, in the above `let body = ` block, adding something like this to the embed:
```javascript
"author": {
    "name": "Anonymous Reporter"
}
```

That will ensure `body.embeds[0].author` is always defined and you can then override its `name` and `icon_url` as desired safely.

2025-02-03 18:14 UTC, KhloeLeclair commented on src/index.js
> +    body.embeds[0].author["name"] = `Anonymous Reporter ${reporterId}`;
Same as previous, `body.embeds[0].author` is undefined.

2025-02-03 18:14 UTC, KhloeLeclair commented on src/index.js
> +    body.embeds[0].author["icon_url"] = getAvatarUrl(reporterId);
Same as previous, `body.embeds[0].author` is undefined.

2025-02-03 19:20 UTC, KhloeLeclair approved these changes
Looks good to me now.

2025-02-03 19:37 UTC, philpax commented
Happy to merge as soon as I have some confirmation that we can look at any errors that might occur

2025-02-03 20:23 UTC, merged